# Azure Pipelines YAML for Node.js (Express) backend + React frontend
# Adjust the paths if your frontend is not in 'src' or backend is not in 'backend'.

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  backendPath: 'backend'
  frontendPath: 'src'  # Change to 'frontend' if your React app is in a different folder

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    cd $(frontendPath)
    npm install
    npm run build
  displayName: 'Install & Build Frontend'

- script: |
    cd $(frontendPath)
    npm test -- --passWithNoTests
  displayName: 'Run Frontend Tests (Ignore if None)'
  continueOnError: true

- script: |
    cd $(backendPath)
    npm install
  displayName: 'Install Backend Dependencies'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(frontendPath)/build'
    Contents: '**'
    TargetFolder: '$(backendPath)/public'
  displayName: 'Copy Frontend Build to Backend Public'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(backendPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<YOUR_AZURE_SERVICE_CONNECTION>'
    appName: 'CTS-VibeAppso3801-5'
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
